<a href="https://colab.research.google.com/github/Nikhilsimha31/climatescope-project/blob/feature%2Fdata-exploration/Climate_scope.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***ClimateScope:Visualizing Global Weather Trends and Extreme Events***
***
Project objective
The objective of ClimateScope is to analyze and visually represent global weather patterns using the Global Weather Repository dataset. This project aims to uncover seasonal trends, regional variations, and extreme weather events through interactive and insightful visualizations. By leveraging daily-updated, worldwide weather data, the project will enable users to explore climate behavior over time, compare conditions across regions, and identify anomalies. The ultimate goal is to provide an accessible, data-driven platform that supports climate awareness, decision-making, and further research into global weather dynamics.

***Milestone 1: Data Preparation & Initial Analysis***

In [1]:
#Download the Global Weather Repository dataset from Kaggle by using opendatasets
!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from opendatasets) (4.67.1)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from opendatasets) (1.7.4.5)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from opendatasets) (8.2.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2025.8.3)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.4.3)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (5.29.5)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (0.5.1)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [2]:
import opendatasets as od
od.download("https://www.kaggle.com/datasets/nelgiriyewithana/global-weather-repository/data")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: Nikhilsimha123
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/nelgiriyewithana/global-weather-repository
Downloading global-weather-repository.zip to ./global-weather-repository

100%|██████████| 7.69M/7.69M [00:00<00:00, 807MB/s]

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('/content/global-weather-repository/GlobalWeatherRepository.csv') #reading the file

***To view total observation and colums present in data set***

In [5]:
df.shape # to see total observation and colums present in data set

(97045, 41)

In [6]:
pd.set_option('display.max_columns', 41) # to see all columns

In [7]:
df.head() # to see top 5 row's

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,wind_mph,wind_kph,wind_degree,wind_direction,pressure_mb,pressure_in,precip_mm,precip_in,humidity,cloud,feels_like_celsius,feels_like_fahrenheit,visibility_km,visibility_miles,uv_index,gust_mph,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,8.3,13.3,338,NNW,1012.0,29.89,0.0,0.00,24,30,25.3,77.5,10.0,6.0,7.0,9.5,15.3,277.0,103.0,1.1,0.2,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,6.9,11.2,320,NW,1012.0,29.88,0.1,0.00,94,75,19.0,66.2,10.0,6.0,5.0,11.4,18.4,193.6,97.3,0.9,0.1,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,9.4,15.1,280,W,1011.0,29.85,0.0,0.00,29,0,24.6,76.4,10.0,6.0,5.0,13.9,22.3,540.7,12.2,65.1,13.4,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,7.4,11.9,215,SW,1007.0,29.75,0.3,0.01,61,100,3.8,38.9,2.0,1.0,2.0,8.5,13.7,170.2,64.4,1.6,0.2,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,8.1,13.0,150,SSE,1011.0,29.85,0.0,0.00,89,50,28.7,83.6,10.0,6.0,8.0,12.5,20.2,2964.0,19.0,72.7,31.5,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [8]:
df.tail()# to see bottom 5 row's

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,wind_mph,wind_kph,wind_degree,wind_direction,pressure_mb,pressure_in,precip_mm,precip_in,humidity,cloud,feels_like_celsius,feels_like_fahrenheit,visibility_km,visibility_miles,uv_index,gust_mph,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
97040,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1758960000,2025-09-27 04:00,26.2,79.2,Clear,4.0,6.5,180,S,1010.0,29.83,0.00,0.00,89,25,29.0,84.3,10.0,6.0,0.0,8.5,13.6,1557.70,65.0,25.900,6.475,22.200,22.385,2,2,06:16 AM,06:20 PM,10:46 AM,10:25 PM,Waxing Crescent,24
97041,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1758959100,2025-09-27 14:45,34.2,93.6,Partly cloudy,4.0,6.5,322,NW,1010.0,29.83,0.65,0.03,56,50,45.2,113.4,10.0,6.0,6.6,5.1,8.3,1045.25,34.0,36.630,26.085,33.485,33.670,2,3,05:47 AM,05:48 PM,10:13 AM,09:07 PM,Waxing Crescent,21
97042,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1758959100,2025-09-27 10:45,23.3,74.0,Sunny,15.9,25.6,61,ENE,1015.0,29.96,0.00,0.00,20,0,22.8,73.0,10.0,6.0,8.4,18.3,29.4,299.70,77.0,1.850,4.625,27.935,81.585,2,3,05:53 AM,05:56 PM,10:16 AM,09:35 PM,Waxing Crescent,22
97043,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1758959100,2025-09-27 09:45,23.4,74.2,Sunny,13.0,20.9,74,ENE,1018.0,30.05,0.00,0.00,45,7,24.8,76.6,10.0,6.0,3.9,14.9,24.0,358.90,81.0,1.295,1.110,17.575,17.945,2,2,05:53 AM,06:03 PM,09:18 AM,10:48 PM,Waxing Crescent,22
97044,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1758959100,2025-09-27 09:45,20.5,69.0,Sunny,8.1,13.0,68,ENE,1020.0,30.13,0.00,0.00,56,25,20.5,69.0,10.0,6.0,4.9,9.3,14.9,569.80,89.0,3.885,0.925,37.185,37.555,2,4,05:41 AM,05:53 PM,09:01 AM,10:42 PM,Waxing Crescent,22

In [9]:
df.info()#Inspect dataset structure, data types, and key variable

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97045 entries, 0 to 97044
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       97045 non-null  object
 1   location_name                 97045 non-null  object
 2   latitude                      97045 non-null  float64
 3   longitude                     97045 non-null  float64
 4   timezone                      97045 non-null  object
 5   last_updated_epoch            97045 non-null  int64
 6   last_updated                  97045 non-null  object
 7   temperature_celsius           97045 non-null  float64
 8   temperature_fahrenheit        97045 non-null  float64
 9   condition_text                97045 non-null  object
 10  wind_mph                      97045 non-null  float64
 11  wind_kph                      97045 non-null  float64
 12  wind_degree                   97045 non-null  int64
 13  wind_direction                97045 non-null  object
 14  pressure_mb                   97045 non-null  float64
 15  pressure_in                   97045 non-null  float64
 16  precip_mm                     97045 non-null  float64
 17  precip_in                     97045 non-null  float64
 18  humidity                      97045 non-null  int64
 19  cloud                         97045 non-null  int64
 20  feels_like_celsius            97045 non-null  float64
 21  feels_like_fahrenheit         97045 non-null  float64
 22  visibility_km                 97045 non-null  float64
 23  visibility_miles              97045 non-null  float64
 24  uv_index                      97045 non-null  float64
 25  gust_mph                      97045 non-null  float64
 26  gust_kph                      97045 non-null  float64
 27  air_quality_Carbon_Monoxide   97045 non-null  float64
 28  air_quality_Ozone             97045 non-null  float64
 29  air_quality_Nitrogen_dioxide  97045 non-null  float64
 30  air_quality_Sulphur_dioxide   97045 non-null  float64
 31  air_quality_PM2.5             97045 non-null  float64
 32  air_quality_PM10              97045 non-null  float64
 33  air_quality_us-epa-index      97045 non-null  int64
 34  air_quality_gb-defra-index    97045 non-null  int64
 35  sunrise                       97045 non-null  object
 36  sunset                        97045 non-null  object
 37  moonrise                      97045 non-null  object
 38  moonset                       97045 non-null  object
 39  moon_phase                    97045 non-null  object
 40  moon_illumination             97045 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 30.4+ MB

In [10]:
df.nunique() # to see number of unique values present in each column

country                           211
location_name                     254
latitude                          394
longitude                         399
timezone                          197
last_updated_epoch                947
last_updated                    16469
temperature_celsius               655
temperature_fahrenheit           1080
condition_text                     47
wind_mph                          180
wind_kph                          180
wind_degree                       360
wind_direction                     16
pressure_mb                        89
pressure_in                       207
precip_mm                         598
precip_in                          73
humidity                           99
cloud                             101
feels_like_celsius                767
feels_like_fahrenheit            1300
visibility_km                      69
visibility_miles                   13
uv_index                          163
gust_mph                          499
gust_kph                          755
air_quality_Carbon_Monoxide      3907
air_quality_Ozone                 635
air_quality_Nitrogen_dioxide     1740
air_quality_Sulphur_dioxide      1740
air_quality_PM2.5                3653
air_quality_PM10                 5395
air_quality_us-epa-index            6
air_quality_gb-defra-index         10
sunrise                           458
sunset                            544
moonrise                         1441
moonset                          1441
moon_phase                          8
moon_illumination                 101
dtype: int64

In [11]:
df.drop_duplicates() #droping the duplicates from datt set

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,wind_mph,wind_kph,wind_degree,wind_direction,pressure_mb,pressure_in,precip_mm,precip_in,humidity,cloud,feels_like_celsius,feels_like_fahrenheit,visibility_km,visibility_miles,uv_index,gust_mph,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,8.3,13.3,338,NNW,1012.0,29.89,0.00,0.00,24,30,25.3,77.5,10.0,6.0,7.0,9.5,15.3,277.00,103.0,1.100,0.200,8.400,26.600,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,6.9,11.2,320,NW,1012.0,29.88,0.10,0.00,94,75,19.0,66.2,10.0,6.0,5.0,11.4,18.4,193.60,97.3,0.900,0.100,1.100,2.000,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,9.4,15.1,280,W,1011.0,29.85,0.00,0.00,29,0,24.6,76.4,10.0,6.0,5.0,13.9,22.3,540.70,12.2,65.100,13.400,10.400,18.400,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,7.4,11.9,215,SW,1007.0,29.75,0.30,0.01,61,100,3.8,38.9,2.0,1.0,2.0,8.5,13.7,170.20,64.4,1.600,0.200,0.700,0.900,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,8.1,13.0,150,SSE,1011.0,29.85,0.00,0.00,89,50,28.7,83.6,10.0,6.0,8.0,12.5,20.2,2964.00,19.0,72.700,31.500,183.400,262.300,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97040,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1758960000,2025-09-27 04:00,26.2,79.2,Clear,4.0,6.5,180,S,1010.0,29.83,0.00,0.00,89,25,29.0,84.3,10.0,6.0,0.0,8.5,13.6,1557.70,65.0,25.900,6.475,22.200,22.385,2,2,06:16 AM,06:20 PM,10:46 AM,10:25 PM,Waxing Crescent,24
97041,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1758959100,2025-09-27 14:45,34.2,93.6,Partly cloudy,4.0,6.5,322,NW,1010.0,29.83,0.65,0.03,56,50,45.2,113.4,10.0,6.0,6.6,5.1,8.3,1045.25,34.0,36.630,26.085,33.485,33.670,2,3,05:47 AM,05:48 PM,10:13 AM,09:07 PM,Waxing Crescent,21
97042,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1758959100,2025-09-27 10:45,23.3,74.0,Sunny,15.9,25.6,61,ENE,1015.0,29.96,0.00,0.00,20,0,22.8,73.0,10.0,6.0,8.4,18.3,29.4,299.70,77.0,1.850,4.625,27.935,81.585,2,3,05:53 AM,05:56 PM,10:16 AM,09:35 PM,Waxing Crescent,22
97043,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1758959100,2025-09-27 09:45,23.4,74.2,Sunny,13.0,20.9,74,ENE,1018.0,30.05,0.00,0.00,45,7,24.8,76.6,10.0,6.0,3.9,14.9,24.0,358.90,81.0,1.295,1.110,17.575,17.945,2,2,05:53 AM,06:03 PM,09:18 AM,10:48 PM,Waxing Crescent,22
97044,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1758959100,2025-09-27 09:45,20.5,69.0,Sunny,8.1,13.0,68,ENE,1020.0,30.13,0.00,0.00,56,25,20.5,69.0,10.0,6.0,4.9,9.3,14.9,569.80,89.0,3.885,0.925,37.185,37.555,2,4,05:41 AM,05:53 PM,09:01 AM,10:42 PM,Waxing Crescent,22

In [12]:
df.isnull().sum() # finding the number of null vales presend in each column

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [13]:
df.describe(include="all") #understanding the data set by using describe

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,wind_mph,wind_kph,wind_degree,wind_direction,pressure_mb,pressure_in,precip_mm,precip_in,humidity,cloud,feels_like_celsius,feels_like_fahrenheit,visibility_km,visibility_miles,uv_index,gust_mph,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
count,97045,97045,97045.000000,97045.000000,97045,9.704500e+04,97045,97045.000000,97045.000000,97045,97045.000000,97045.000000,97045.000000,97045,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045.000000,97045,97045,97045,97045,97045,97045.000000
unique,211,254,NaN,NaN,197,NaN,16469,NaN,NaN,47,NaN,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,458,544,1441,1441,8,NaN
top,Bulgaria,Kabul,NaN,NaN,Asia/Bangkok,NaN,2024-11-04 10:00,NaN,NaN,Partly cloudy,NaN,NaN,NaN,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05:57 AM,06:28 PM,No moonrise,No moonset,Waxing Gibbous,NaN
freq,1063,499,NaN,NaN,1905,NaN,44,NaN,NaN,30292,NaN,NaN,NaN,9198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1078,932,3302,3110,21350,NaN
mean,NaN,NaN,19.145186,22.115716,NaN,1.737455e+09,NaN,22.791571,73.026547,NaN,8.244292,13.271171,170.884250,NaN,1013.961482,29.941632,0.140909,0.005353,64.133546,39.332701,23.837024,74.900213,9.638660,5.705477,3.891631,11.534286,18.564659,517.485783,62.823629,15.800620,11.269702,26.168241,53.799741,1.760936,2.762069,NaN,NaN,NaN,NaN,NaN,49.758566
std,NaN,NaN,24.457909,65.820313,NaN,1.247255e+07,NaN,8.898810,16.017660,NaN,7.890675,12.696435,102.712791,NaN,11.397183,0.336504,0.600263,0.023717,24.190492,33.744598,10.608738,19.093884,2.515246,1.563437,3.619782,9.131024,14.695027,845.401827,32.283652,26.058807,40.864757,40.869172,164.384723,0.982031,2.568669,NaN,NaN,NaN,NaN,NaN,35.146673
min,NaN,NaN,-41.300000,-175.200000,NaN,1.715849e+09,NaN,-24.900000,-12.800000,NaN,2.200000,3.600000,1.000000,NaN,947.000000,27.960000,0.000000,0.000000,2.000000,0.000000,-35.600000,-32.100000,0.000000,0.000000,0.000000,2.200000,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,3.750000,-6.836100,NaN,1.726743e+09,NaN,18.100000,64.600000,NaN,4.000000,6.500000,83.000000,NaN,1010.000000,29.830000,0.000000,0.000000,47.000000,0.000000,18.100000,64.600000,10.000000,6.000000,0.600000,6.600000,10.500000,238.650000,42.000000,1.295000,0.800000,7.400000,10.833000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,15.000000
50%,NaN,NaN,17.250000,23.316700,NaN,1.737455e+09,NaN,25.000000,77.000000,NaN,6.900000,11.200000,165.000000,NaN,1013.000000,29.920000,0.000000,0.000000,69.000000,26.000000,26.000000,78.700000,10.000000,6.000000,3.000000,9.900000,15.900000,327.450000,60.000000,4.900000,2.405000,15.170000,22.200000,1.000000,2.000000,NaN,NaN,NaN,NaN,NaN,50.000000
75%,NaN,NaN,40.400000,50.580000,NaN,1.748250e+09,NaN,28.300000,82.900000,NaN,11.400000,18.400000,256.000000,NaN,1017.000000,30.050000,0.030000,0.000000,83.000000,75.000000,30.800000,87.400000,10.000000,6.000000,6.900000,15.200000,24.400000,507.400000,79.400000,17.945000,9.065000,29.970000,46.065000,2.000000,3.000000,NaN,NaN,NaN,NaN,NaN,85.000000
max,NaN,NaN,64.150000,179.220000,NaN,1.758960e+09,NaN,49.200000,120.600000,NaN,1841.200000,2963.200000,360.000000,NaN,3006.000000,88.770000,42.240000,1.660000,100.000000,100.000000,51.200000,124.200000,32.000000,19.000000,16.300000,1845.700000,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,NaN,NaN,NaN,NaN,NaN,100.000000

In [14]:
df_clean = df.drop(columns=[
    "temperature_fahrenheit",    #actually represent the same measurement but in different units
    "feels_like_fahrenheit",     #total 7 of them
    "wind_mph",
    "gust_mph",
    "pressure_in",
    "precip_in",
    "visibility_miles"
])
from IPython.display import display
display(df_clean.head())

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,wind_degree,wind_direction,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,Partly Cloudy,13.3,338,NNW,1012.0,0.0,24,30,25.3,10.0,7.0,15.3,277.0,103.0,1.1,0.2,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,Partly cloudy,11.2,320,NW,1012.0,0.1,94,75,19.0,10.0,5.0,18.4,193.6,97.3,0.9,0.1,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,Sunny,15.1,280,W,1011.0,0.0,29,0,24.6,10.0,5.0,22.3,540.7,12.2,65.1,13.4,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,Light drizzle,11.9,215,SW,1007.0,0.3,61,100,3.8,2.0,2.0,13.7,170.2,64.4,1.6,0.2,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,Partly cloudy,13.0,150,SSE,1011.0,0.0,89,50,28.7,10.0,8.0,20.2,2964.0,19.0,72.7,31.5,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [15]:
df_clean["last_updated"] = pd.to_datetime(df_clean["last_updated"]) #last_updated column is still a string (object dtype), not a proper datetime
                                                                    #Converting  column to datetime

In [16]:
#same coverting srting data type into datatime data type
# why python detecting string data type because  in data set columes (moonrise and moonset) data has  "No moonrise" doesn’t match the time format.
# so i make it Nat and replace with None
df_clean["sunrise"]  = pd.to_datetime(df_clean["sunrise"],  format="%I:%M %p", errors="coerce").dt.time.astype(str).replace("NaT", "None")
df_clean["sunset"]   = pd.to_datetime(df_clean["sunset"],   format="%I:%M %p", errors="coerce").dt.time.astype(str).replace("NaT", "None")
df_clean["moonrise"] = pd.to_datetime(df_clean["moonrise"], format="%I:%M %p", errors="coerce").dt.time.astype(str).replace("NaT", "None")
df_clean["moonset"]  = pd.to_datetime(df_clean["moonset"],  format="%I:%M %p", errors="coerce").dt.time.astype(str).replace("NaT", "None")

In [19]:
df_clean.to_csv('df_clean.csv', index=False) #Save the cleaned dataframe into a CSV file named 'df_clean.csv' .

In [20]:
df1=pd.read_csv('df_clean.csv') #reading the 'df_clean.csv' file.

In [21]:
df1.head() # seeing the top 5 row's in 'df_clean.csv'  file.

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,wind_degree,wind_direction,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,338,NNW,1012.0,0.0,24,30,25.3,10.0,7.0,15.3,277.0,103.0,1.1,0.2,8.4,26.6,1,1,04:50:00,18:50:00,12:12:00,01:11:00,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,Partly cloudy,11.2,320,NW,1012.0,0.1,94,75,19.0,10.0,5.0,18.4,193.6,97.3,0.9,0.1,1.1,2.0,1,1,05:21:00,19:54:00,12:58:00,02:14:00,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,Sunny,15.1,280,W,1011.0,0.0,29,0,24.6,10.0,5.0,22.3,540.7,12.2,65.1,13.4,10.4,18.4,1,1,05:40:00,19:50:00,13:15:00,02:14:00,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,Light drizzle,11.9,215,SW,1007.0,0.3,61,100,3.8,2.0,2.0,13.7,170.2,64.4,1.6,0.2,0.7,0.9,1,1,06:31:00,21:11:00,14:12:00,03:31:00,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,Partly cloudy,13.0,150,SSE,1011.0,0.0,89,50,28.7,10.0,8.0,20.2,2964.0,19.0,72.7,31.5,183.4,262.3,5,10,06:12:00,17:55:00,13:17:00,00:38:00,Waxing Gibbous,55

In [22]:
#Aggregate / Filter Data (Daily → Monthly Averages)
df_monthly = (
    df_clean
    .set_index("last_updated")
    .groupby("country")
    .resample("ME")
    .mean(numeric_only=True)
    .reset_index()
)
display(df_monthly.head())

,country,last_updated,latitude,longitude,last_updated_epoch,temperature_celsius,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
0,Afghanistan,2024-05-31,34.52,69.18,1.716478e+09,20.305882,11.517647,127.941176,1010.000000,0.108824,38.058824,31.764706,20.358824,9.764706,3.764706,16.141176,1424.094118,77.452941,16.400000,0.588235,7.894118,17.411765,1.000000,1.117647,78.647059
1,Afghanistan,2024-06-30,34.52,69.18,1.718503e+09,25.590000,17.110000,126.833333,1004.900000,0.072667,24.833333,20.833333,24.603333,9.800000,6.500000,20.336667,1481.570000,87.650000,17.000000,0.530000,7.380000,16.786667,1.000000,1.066667,49.800000
2,Afghanistan,2024-07-31,34.52,69.18,1.721101e+09,31.303448,20.731034,103.862069,998.000000,0.000345,17.931034,13.068966,29.475862,10.000000,7.758621,23.841379,624.758621,119.327586,4.700000,0.306897,9.065517,23.596552,1.068966,1.137931,43.758621
3,Afghanistan,2024-08-31,34.52,69.18,1.723811e+09,30.848387,20.196774,57.709677,1001.258065,0.037097,20.548387,11.903226,29.316129,9.774194,7.483871,23.238710,605.025806,119.612903,3.641935,0.306452,9.638710,22.674194,1.032258,1.225806,45.548387
4,Afghanistan,2024-09-30,34.52,69.18,1.726442e+09,28.216667,12.223333,67.566667,1004.800000,0.014333,13.733333,13.066667,26.390000,9.833333,7.000000,14.063333,376.173333,138.046667,2.523667,13.977000,20.996833,42.791667,1.666667,2.366667,46.100000

In [23]:
df_monthly.to_csv('df_monthly.csv', index=False) #Save the monthly dataframe into a CSV file named 'df_monthly.csv' .

In [24]:
df2=pd.read_csv('df_monthly.csv') # reading the file

In [25]:
df2.head() # seeing tos 5 row'5 in 'df_monthly.csv' file

,country,last_updated,latitude,longitude,last_updated_epoch,temperature_celsius,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
0,Afghanistan,2024-05-31,34.52,69.18,1.716478e+09,20.305882,11.517647,127.941176,1010.000000,0.108824,38.058824,31.764706,20.358824,9.764706,3.764706,16.141176,1424.094118,77.452941,16.400000,0.588235,7.894118,17.411765,1.000000,1.117647,78.647059
1,Afghanistan,2024-06-30,34.52,69.18,1.718503e+09,25.590000,17.110000,126.833333,1004.900000,0.072667,24.833333,20.833333,24.603333,9.800000,6.500000,20.336667,1481.570000,87.650000,17.000000,0.530000,7.380000,16.786667,1.000000,1.066667,49.800000
2,Afghanistan,2024-07-31,34.52,69.18,1.721101e+09,31.303448,20.731034,103.862069,998.000000,0.000345,17.931034,13.068966,29.475862,10.000000,7.758621,23.841379,624.758621,119.327586,4.700000,0.306897,9.065517,23.596552,1.068966,1.137931,43.758621
3,Afghanistan,2024-08-31,34.52,69.18,1.723811e+09,30.848387,20.196774,57.709677,1001.258065,0.037097,20.548387,11.903226,29.316129,9.774194,7.483871,23.238710,605.025806,119.612903,3.641935,0.306452,9.638710,22.674194,1.032258,1.225806,45.548387
4,Afghanistan,2024-09-30,34.52,69.18,1.726442e+09,28.216667,12.223333,67.566667,1004.800000,0.014333,13.733333,13.066667,26.390000,9.833333,7.000000,14.063333,376.173333,138.046667,2.523667,13.977000,20.996833,42.791667,1.666667,2.366667,46.100000

In [26]:
#Aggregate / Filter Data (Daily → yearly Averages)
df_yearly = (
    df_clean                            #Aggregate / Filter
    .set_index('last_updated')
    .groupby('country')
    .resample('YE')
    .mean(numeric_only=True)
    .reset_index()
)
df_yearly.head()

,country,last_updated,latitude,longitude,last_updated_epoch,temperature_celsius,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
0,Afghanistan,2024-12-31,34.518703,69.181297,1.725745e+09,22.696943,12.113974,99.257642,1008.096070,0.038603,22.497817,16.419214,21.810044,9.890830,5.057205,15.079476,774.743013,107.629258,7.655328,7.974389,14.860000,28.745873,1.388646,1.772926,48.672489
1,Afghanistan,2025-12-31,34.516700,69.183300,1.747343e+09,21.127407,8.044074,120.603704,1009.355556,0.037741,25.929630,16.055556,19.612222,9.803704,7.067037,10.092963,744.508519,126.362963,7.643926,12.595074,25.286759,65.035037,1.896296,2.688889,50.755556
2,Albania,2024-12-31,41.329017,19.819568,1.725745e+09,25.022271,11.429694,237.855895,1014.899563,0.169651,49.532751,26.205240,25.559389,9.851092,5.010917,15.961572,257.638646,83.346288,10.230000,4.604236,13.593777,18.724323,1.349345,1.672489,48.606987
3,Albania,2025-12-31,41.327500,19.818900,1.747343e+09,21.586667,7.922593,223.607407,1016.444444,0.087741,48.962963,25.896296,21.465926,9.985185,3.850741,9.811852,306.284630,74.751852,17.453722,9.004019,19.488722,26.176815,1.666667,2.151852,50.751852
4,Algeria,2024-12-31,36.761224,3.050237,1.725762e+09,25.154386,15.312719,174.412281,1017.035088,0.025351,55.407895,28.048246,26.760526,9.745614,4.786404,20.516228,307.305263,88.343860,30.107917,12.673136,18.584364,35.214364,1.574561,2.122807,48.394737

In [28]:
# Take user input for a date and country, then filter the dataframe
# to show weather information for that specific day and country.
# The result is displayed as a table
input_date = input("Enter date (YYYY-MM-DD): ")
input_country = input("Enter country: ")

day_info = df_clean[
    (df_clean["country"] == input_country) &
    (df_clean["last_updated"].dt.date == pd.to_datetime(input_date).date())
]

from IPython.display import display
display(day_info)

Enter date (YYYY-MM-DD): 2024-12-31
Enter country: Albania

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,wind_degree,wind_direction,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
44275,Albania,Tirana,41.3275,19.8189,Europe/Tirane,1735642800,2024-12-31 12:00:00,13.4,Sunny,4.7,282,WNW,1031.0,0.0,54,0,13.7,10.0,1.5,5.4,371.85,62.0,39.405,25.715,35.705,44.4,2,3,07:07:00,16:21:00,07:55:00,16:38:00,Waxing Crescent,0